### ISSUE TITLE
PC's Vision Brightens When They Select Their Own Token

### ISSUE THREAD

**Issue by Dumbhuman** [Voldemalort/darker-vision-for-5e#1]
![darkvisionbug](https://user-images.githubusercontent.com/63615591/87180492-7cec5480-c295-11ea-9d93-11aef5bef091.gif)

Ideally, a player shouldn't have their own vision brighten when they select themselves.

**Comment by Voldemalort** [comment]
I'm not sure I agree. When your token isn't selected you see dim and bright light the way it truly is in the world. When you select a token you see it from that token's perspective. I don't plan to change that.

**Comment by Dumbhuman** [comment]
Shouldn't the dim vision granted by DarkerVision be equivalent to core dim vision when there aren't light sources around though?  Currently when the module is enabled, selecting a token turns their dim vision radius into something between dim vision and bright vision, brightening what they can see in the absence of any light sources (which seems to run counter to the intent to have a more technically accurate darkvision).

Standard core behavior when selecting a token with Dim Vision (no luminance change):
![StandardSelection](https://user-images.githubusercontent.com/63615591/87230304-f05c9780-c363-11ea-9c86-83ad8e913937.gif)

Current DarkerVision behavior when selecting a token with Dim Vision:
![DarkerVisionSelection](https://user-images.githubusercontent.com/63615591/87230307-ff434a00-c363-11ea-8f02-b45fe0711b16.gif)

If it's a technical hurdle that can't be overcome easily, I understand completely.  If it's instead a personal preference for slightly brighter dim vision, could it perhaps be added as an optional setting for those who'd like to retain the luminance values of core dim vision in areas of darkness?

**Comment by Voldemalort** [comment]
This is a technical constraint. To brighten other light we need to use a subtract filter on the division radius. If the division were exactly 50% alpha it would look exactly the same, but it's 90% * 50% alpha. I could adjust the alpha to make the dim light look identical, but there would be a difference between the brightened dim light and true bright light. It was easier to see a difference between brightened dim light and true dim light in that state than it was for dim light and subtract-filter dim-sight, so I made the choice to keep brightened dim light and bright light closer.

These dimvision/dim light differences are much harder to detect with an actual background map while the brightened dim light/true bright light differences were still easy to see.

**Comment by Voldemalort** [comment]
Also, keep in mind that adding alpha to any light source means dim and bright lights could look drastically different. I understand we're mostly talking about default settings for dim and bright lights.

**Comment by DarKDinDoN** [comment]
Hello,  
Was looking for the same issue.  

Isn't it the case when the user has only one controlled character/token?  
Since the user can only control one token, selecting or deselecting this token shouldn't change the vision, don't you think?
I think this is how Core is handling this.

I imagine that selecting or deselecting the token would render the same view. The token view.
But if the user has multiple controlled tokens that would default to what is currently implemented. Just like for the GM view.
