### ISSUE TITLE
Grey-scale by character?

### ISSUE THREAD

**Issue by Hypersapien** [Voldemalort/darker-vision-for-5e#4]
I really like this module, especially the Grey-Scale Mode.

I realize it's just experimental (hence the name) but is there any chance we could get it toggleable on and off on a per-character basis? Have some characters have grayscale darkvision and others not? Since there are types of non-normal vision that allow full color vision, for instance the Warlock Invocation "Devil's Sight".

**Comment by Voldemalort** [comment]
I don't intend on making further changes to the 0.6.x version of this module and it's unlikely that I'll make a 0.7.x version due to new vision and lighting complexity and my lack of knowledge in writing custom shaders.
