### ISSUE TITLE
Foundry version 0.7.3 - doesn't update light when moving

### ISSUE THREAD

**Issue by dolence** [Voldemalort/darker-vision-for-5e#5]
This module is broken oOn the newest beta version of Foundry VTT. When moving token the lights doesn't redraw/get update.

**Comment by Voldemalort** [comment]
I don't intend on making further changes to the 0.6.x version of this module and it's unlikely that I'll make a 0.7.x version due to new vision and lighting complexity and my lack of knowledge in writing custom shaders.
