### ISSUE TITLE
[Feature request] Low-light vision

### ISSUE THREAD

**Issue by PalaNolho** [Voldemalort/darker-vision-for-5e#6]
Would you be able to add the concept of "Low-light" vision to your module?
The idea would be to have these 2 types of visions:

- **Darkvision** (no change, continues to work as you implemented)
Dark -> Dim &  Dim -> Bright, 
- **Low-light Vision** (new mode)
Dark -> Dark & Dim-> Bright

From the fields that are available on the vision config at the moment (and in order to not have to add more custom fields...), I think an easy way to do it would be to set both dim and bright vision of the token to the same value and using this to make the module understand "oh, this token has low-light vision.

So, if a token has 
dim = 60 and bright **different** from dim (generally = 0), then the token has darkvision 60ft and will see accordingly
but if a char has dim = 60 and bright = 60 (**same value**), then he would have low-light.

Many thanks.

**Comment by Voldemalort** [comment]
I don't intend on making further changes to the 0.6.x version of this module and it's unlikely that I'll make a 0.7.x version due to new vision and lighting complexity and my lack of knowledge in writing custom shaders.
