### ISSUE TITLE
O.7.5 Compatibility Inquiry

### ISSUE THREAD

**Issue by Norc** [Voldemalort/darker-vision-for-5e#7]
Hello,

I know this probably doesn't come as a surprise to you, but with the extensive vision changes in 0.7.5 this module is now quite broken. Based on the reaction in the various discord channels, it seems pretty popular!

Do you have any intent/plans to update this to 0.7.5? Thanks for creating this module and your time.

**Comment by Dumbhuman** [comment]
Just adding a note to say I'm crossing my fingers in hopes that there will be a DarkerVision update (since Norc beat me to opening the issue myself)!  DarkerVision not working in 0.7.5 is one of the main reasons I'm staying with Foundry VTT version 0.6.6 currently.

**Comment by Voldemalort** [comment]
I don't intend on making further changes to the 0.6.x version of this module and it's unlikely that I'll make a 0.7.x version due to new vision and lighting complexity and my lack of knowledge in writing custom shaders.
